<?php

namespace App\Mqtt\Pagerungan;

use Carbon\Carbon;
use Hyperf\Utils\Str;
use Hyperf\Utils\Codec\Json;

class Panasia
{
    protected string $message;

    public function __construct(string $message) {
       
        $this->message = $message;
    }
    
    public function extract()
    {
        $data = Json::decode($this->message);
        $values = $data['panasia'];

        return [
            'cargo' => [
                'terminal_time' => Carbon::now()->format('Y-m-d H:i:s'),
                'cargo_tank1p_ullage' => $values[0] / 1000,
                'cargo_tank1s_ullage' => $values[1] / 1000,
                'cargo_tank2p_ullage' => $values[2] / 1000,
                'cargo_tank2s_ullage' => $values[3] / 1000,
                'cargo_tank3p_ullage' => $values[4] / 1000,
                'cargo_tank3s_ullage' => $values[5] / 1000,
                'cargo_tank4p_ullage' => $values[6] / 1000,
                'cargo_tank4s_ullage' => $values[7] / 1000,
                'cargo_tank5p_ullage' => $values[8] / 1000,
                'cargo_tank5s_ullage' => $values[9] / 1000,
                'slop_tank_p_ullage' => $values[10] / 1000,
                'slop_tank_s_ullage' => $values[11] / 1000,
                'water_ballast_tank1p_level' => $values[12] / 1000,
                'water_ballast_tank1s_level' => $values[13] / 1000,
                'water_ballast_tank2p_level' => $values[14] / 1000,
                'water_ballast_tank2s_level' => $values[15] / 1000,
                'water_ballast_tank3p_level' => $values[16] / 1000,
                'water_ballast_tank3s_level' => $values[17] / 1000,
                'water_ballast_tank4p_level' => $values[18] / 1000,
                'water_ballast_tank4s_level' => $values[19] / 1000,
                'water_ballast_tank5p_level' => $values[20] / 1000,
                'water_ballast_tank5s_level' => $values[21] / 1000,
                'water_ballast_tank6p_level' => $values[22] / 1000,
                'water_ballast_tank6s_level' => $values[23] / 1000,
                'fore_peak_tank_leve' => $values[24] / 1000,
                'after_peak_tank_level' => $values[25] / 1000,
                'no1_fo_tank_p_level' => $values[26] / 1000,
                'no1_fo_tank_s_level' => $values[27] / 1000,
                'no2_fo_tank_p_level' => $values[28] / 1000,
                'no2_fo_tank_s_level' => $values[29] / 1000,
                'no1_fo_service_tank_level' => $values[30] / 1000,
                'no2_fo_service_tank_level' => $values[31] / 1000,
                'fo_settling_tank_level' => $values[32] / 1000,
                'do_storage_tank_p_level' => $values[33] / 1000,
                'do_storage_tank_s_level' => $values[34] / 1000,
                'no1_do_service_tank_level' => $values[35] / 1000,
                'no2_do_service_tank_level' => $values[36] / 1000,
                'do_setting_tank_level' => $values[37] / 1000,
                'draft_sensor_level' => $values[38] / 1000,
                'draft_mark_level' => $values[39] / 1000,
                'draft_pp_level' => $values[40] / 1000,
                'cargo_tank1p_upper_temp' => $values[41] / 10,
                'cargo_tank1p_middle_temp' => $values[42] / 10,
                'cargo_tank1p_bottom_temp' => $values[43] / 10,
                'cargo_tank1p_pressure' => $values[44],
                'cargo_tank1p_volume' => $values[45],
                'cargo_tank1s_upper_temp' => $values[46] / 10,
                'cargo_tank1s_middle_temp' => $values[47] / 10,
                'cargo_tank1s_bottom_temp' => $values[48] / 10,
                'cargo_tank1s_pressure' => $values[49],
                'cargo_tank1s_volume' => $values[50],
                'cargo_tank2p_upper_temp' => $values[51] / 10,
                'cargo_tank2p_middle_temp' => $values[52] / 10,
                'cargo_tank2p_bottom_temp' => $values[53] / 10,
                'cargo_tank2p_pressure' => $values[54],
                'cargo_tank2p_volume' => $values[55],
                'cargo_tank2s_upper_temp' => $values[56] / 10,
                'cargo_tank2s_middle_temp' => $values[57] / 10,
                'cargo_tank2s_bottom_temp' => $values[58] / 10,
                'cargo_tank2s_pressure' => $values[59],
                'cargo_tank2s_volume' => $values[60],
                'cargo_tank3p_upper_temp' => $values[61] / 10,
                'cargo_tank3p_middle_temp' => $values[62] / 10,
                'cargo_tank3p_bottom_temp' => $values[63] / 10,
                'cargo_tank3p_pressure' => $values[64],
                'cargo_tank3p_volume' => $values[65],
                'cargo_tank3s_upper_temp' => $values[66] / 10,
                'cargo_tank3s_middle_temp' => $values[67] / 10,
                'cargo_tank3s_bottom_temp' => $values[68] / 10,
                'cargo_tank3s_pressure' => $values[69],
                'cargo_tank3s_volume' => $values[70],
                'cargo_tank4p_upper_temp' => $values[71] / 10,
                'cargo_tank4p_middle_temp' => $values[72] / 10,
                'cargo_tank4p_bottom_temp' => $values[73] / 10,
                'cargo_tank4p_pressure' => $values[74],
                'cargo_tank4p_volume' => $values[75],
                'cargo_tank4s_upper_temp' => $values[76] / 10,
                'cargo_tank4s_middle_temp' => $values[77] / 10,
                'cargo_tank4s_bottom_temp' => $values[78] / 10,
                'cargo_tank4s_pressure' => $values[79],
                'cargo_tank4s_volume' => $values[80],
                'cargo_tank5p_upper_temp' => $values[81] / 10,
                'cargo_tank5p_middle_temp' => $values[82] / 10,
                'cargo_tank5p_bottom_temp' => $values[83] / 10,
                'cargo_tank5p_pressure' => $values[84],
                'cargo_tank5p_volume' => $values[85],
                'cargo_tank5s_upper_temp' => $values[86] / 10,
                'cargo_tank5s_middle_temp' => $values[87] / 10,
                'cargo_tank5s_bottom_temp' => $values[88] / 10,
                'cargo_tank5s_pressure' => $values[89],
                'cargo_tank5s_volume' => $values[90],
                'slop_tank_p_upper_temp' => $values[91] / 10,
                'slop_tank_p_middle_temp' => $values[92] / 10,
                'slop_tank_p_bottom_temp' => $values[93] / 10,
                'slop_tank_p_pressure' => $values[94],
                'slop_tank_p_volume' => $values[95],
                'slop_tank_s_upper_temp' => $values[96] / 10,
                'slop_tank_s_middle_temp' => $values[97] / 10,
                'slop_tank_s_bottom_temp' => $values[98] / 10,
                'slop_tank_s_pressure' => $values[99],
                'slop_tank_s_volume' => $values[100],
                'no1_fo_tank_p_volume' => $values[101],
                'no1_fo_tank_s_volume' => $values[102],
                'no2_fo_tank_p_volume' => $values[103],
                'no2_fo_tank_s_volume' => $values[104],
                'no1_fo_service_tank_volume' => $values[105],
                'no2_fo_service_tank_volume' => $values[106],
                'fo_settling_tank_volume' => $values[107],
                'do_storage_tank_p_volume' => $values[108],
                'do_storage_tank_s_volume' => $values[109],
                'no1_do_service_tank_volume' => $values[110],
                'no2_do_service_tank_volume' => $values[111],
                'do_setting_tank_volume' => $values[112],
            ]
        ];
    }

    function arrayToSnake() : array {
        $snake = [];
        foreach($this->mappArray as $in => $val) {
            if(is_null($val)) continue;
            $key = Str::snake(strtolower($val));
            $snake[$key] = $in;
        } 
        return $snake;
    }

    protected $mappArray = [
        'Cargo Tank 1P Ullage',
        'Cargo Tank 1S Ullage',
        'Cargo Tank 2P Ullage',
        'Cargo Tank 2S Ullage',
        'Cargo Tank 3P Ullage',
        'Cargo Tank 3S Ullage',
        'Cargo Tank 4P Ullage',
        'Cargo Tank 4S Ullage',
        'Cargo Tank 5P Ullage',
        'Cargo Tank 5S Ullage',
        'Slop Tank P Ullage',
        'Slop Tank S Ullage',
        'Water Ballast Tank 1P Level',
        'Water Ballast Tank 1S Level',
        'Water Ballast Tank 2P Level',
        'Water Ballast Tank 2S Level',
        'Water Ballast Tank 3P Level',
        'Water Ballast Tank 3S Level',
        'Water Ballast Tank 4P Level',
        'Water Ballast Tank 4S Level',
        'Water Ballast Tank 5P Level',
        'Water Ballast Tank 5S Level',
        'Water Ballast Tank 6P Level',
        'Water Ballast Tank 6S Level',
        'Fore Peak Tank Leve',
        'After Peak Tank Level',
        'No1 FO Tank P Level',
        'No1 FO Tank S Level',
        'No2 FO Tank P Level',
        'No2 FO Tank S Level',
        'No1 FO Service Tank  Level',
        'No2 FO Service Tank Level',
        'FO Settling Tank Level',
        'DO Storage Tank P Level',
        'DO Storage Tank S Level',
        'No1 DO Service Tank Level',
        'No2 DO Service Tank Level',
        'DO Setting Tank Level',
        'Draft Sensor Level',
        'Draft Mark Level',
        'Draft PP Level',
        'Cargo Tank 1P Upper Temp',
        'Cargo Tank 1P Middle Temp',
        'Cargo Tank 1P Bottom Temp',
        'Cargo Tank 1P Pressure',
        'Cargo Tank 1P Volume',
        'Cargo Tank 1S Upper Temp',
        'Cargo Tank 1S Middle Temp',
        'Cargo Tank 1S Bottom Temp',
        'Cargo Tank 1S Pressure',
        'Cargo Tank 1S Volume',
        'Cargo Tank 2P Upper Temp',
        'Cargo Tank 2P Middle Temp',
        'Cargo Tank 2P Bottom Temp',
        'Cargo Tank 2P Pressure',
        'Cargo Tank 2P Volume',
        'Cargo Tank 2S Upper Temp',
        'Cargo Tank 2S Middle Temp',
        'Cargo Tank 2S Bottom Temp',
        'Cargo Tank 2S Pressure',
        'Cargo Tank 2S Volume',
        'Cargo Tank 3P Upper Temp',
        'Cargo Tank 3P Middle Temp',
        'Cargo Tank 3P Bottom Temp',
        'Cargo Tank 3P Pressure',
        'Cargo Tank 3P Volume',
        'Cargo Tank 3S Upper Temp',
        'Cargo Tank 3S Middle Temp',
        'Cargo Tank 3S Bottom Temp',
        'Cargo Tank 3S Pressure',
        'Cargo Tank 3S Volume',
        'Cargo Tank 4P Upper Temp',
        'Cargo Tank 4P Middle Temp',
        'Cargo Tank 4P Bottom Temp',
        'Cargo Tank 4P Pressure',
        'Cargo Tank 4P Volume',
        'Cargo Tank 4S Upper Temp',
        'Cargo Tank 4S Middle Temp',
        'Cargo Tank 4S Bottom Temp',
        'Cargo Tank 4S Pressure',
        'Cargo Tank 4S Volume',
        'Cargo Tank 5P Upper Temp',
        'Cargo Tank 5P Middle Temp',
        'Cargo Tank 5P Bottom Temp',
        'Cargo Tank 5P Pressure',
        'Cargo Tank 5P Volume',
        'Cargo Tank 5S Upper Temp',
        'Cargo Tank 5S Middle Temp',
        'Cargo Tank 5S Bottom Temp',
        'Cargo Tank 5S Pressure',
        'Cargo Tank 5S Volume',
        'Slop Tank P Upper Temp',
        'Slop Tank P Middle Temp',
        'Slop Tank P Bottom Temp',
        'Slop Tank P Pressure',
        'Slop Tank P Volume',
        'Slop Tank S Upper Temp',
        'Slop Tank S Middle Temp',
        'Slop Tank S Bottom Temp',
        'Slop Tank S Pressure',
        'Slop Tank S Volume',
        'No1 FO Tank P Volume',
        'No1 FO Tank S Volume',
        'No2 FO Tank P Volume',
        'No2 FO Tank S Volume',
        'No1 FO Service Tank  Volume',
        'No2 FO Service Tank Volume',
        'FO Settling Tank Volume',
        'DO Storage Tank P Volume',
        'DO Storage Tank S Volume',
        'No1 DO Service Tank Volume',
        'No2 DO Service Tank Volume',
        'DO Setting Tank Volume',
    ];
}